name: Publish Retype powered website to GitHub
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to the retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: retypeapp/action-build@master

      - uses: retypeapp/action-github-pages@master
        with:
          branch: gh-pages
          update-branch: true
